FROM lpenz/debian-squeeze-amd64

RUN echo "root:agoodserverpasswordtopreventanyattackbecauseitisverylong" | chpasswd

WORKDIR /root
RUN apt-get update -y && \
apt-get install -yq --force-yes wget debconf-utils ssh vim telnet && \
echo "proftpd-basic shared/proftpd/inetd_or_standalone select standalone" | debconf-set-selections && \
wget http://launchpadlibrarian.net/58185345/proftpd-basic_1.3.3a-4_amd64.deb && \
apt-get -fyq install --force-yes libcap2 ucf update-inetd libfile-temp-perl libfile-copy-recursive-perl perl libdb4.7 && \
dpkg -i proftpd-basic_1.3.3a-4_i386.deb && \
rm -f proftpd-basic_1.3.3a-4_amd64.deb

#EXPOSE 20
#EXPOSE 21
#EXPOSE 22

ENTRYPOINT service proftpd start && service ssh start && sleep infinity

