FROM lpenz/debian-squeeze-i386

RUN echo "root:agoodserverpasswordtopreventanyattackbecauseitisverylong" | chpasswd

WORKDIR /root
RUN echo "PS1='${debian_chroot:+($debian_chroot)}\u@ftp:\w\$ '" >> .bashrc
COPY proftpd-basic_1.3.3a-4_i386.deb ./
RUN apt-get update -y && \
apt-get install -yq --force-yes wget debconf-utils ssh vim telnet && \
echo "proftpd-basic shared/proftpd/inetd_or_standalone select standalone" | debconf-set-selections && \
apt-get -fyq install --force-yes libcap2 ucf update-inetd libfile-temp-perl libfile-copy-recursive-perl perl libdb4.7 && \
dpkg -i proftpd-basic_1.3.3a-4_i386.deb && \
rm -f proftpd-basic_1.3.3a-4_i386.deb

#EXPOSE 20
#EXPOSE 21
#EXPOSE 22

ENTRYPOINT service proftpd start && service ssh start && sleep infinity

